#!/bin/bash
. $HOME/.nvm/nvm.sh

TARGET="/home/ubuntu/userflow"
GIT_DIR="/home/ubuntu/userflow.git"

# Colors
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
no_color='\033[0m'

while read oldrev newrev ref
do
	# Get branch name
        BRANCH=$(echo "$ref" | cut -d/ -f3)
        # checking out the branch you pushed to deploy)
        echo -e "\n${green}Ref $ref received. Deploying ${BRANCH} branch to production...${no_color}\n"
        if git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f "$BRANCH"; then
                #Install dependencies
                # Go to work-tree
                echo -e "\n${green}Running yarn install${no_color}\n"
                cd "${TARGET}" && yarn
                # Run migrations
                echo -e "\n${green}Run migrations${no_color}\n"
                yarn prisma:generate
                # Restart pm2
        	echo -e "\n${green}Restarting pm2${no_color}\n"
                pm2 restart userflow
            echo -e "\n${green}-------------------${no_color}\n"
            echo -e "\n${green} Latest code is deployed ${no_color}\n"
            echo -e "\n${green}-------------------${no_color}\n"
        else
                echo -e "\n${red}Some error occured. Exiting${no_color}"
                exit 1
        fi
done
exit 0